const PROJETS = {
    "info_1": {
      "titre": "PORTRAIT GRAPHIQUE",
      "categorie": "GRAPHISME",
      "type": "Personnel",
      "duree": "inconnue",
      "equipe": "seule",
      "annee": "2017",
      "contexte":"À une période où les portraits graphiques (ou outline drawing) étaient à la mode sur les réseaux sociaux, je m'y suis moi-même essayée et ait réalisé ce portrait sur Ipad. <br> <br> Logiciel utilisé: Adobe draw",
      "plus":"",
      "lien_prec":"progra_1",
      "lien_suiv":"info_2",
      "retour":"infographie",
      
    },

    "info_2": {
      "titre": "PORTRAIT GRAPHIQUE",
      "categorie": "GRAPHISME",
      "type": "Personnel",
      "duree": "inconnue",
      "equipe": "seule",
      "annee": "2017",
     "contexte": "Portrait graphique de mon chien Moka réalisé sur Ipad <br> <br> Logiciel utilisé: Adobe draw ",
     "plus":"",
     "lien_prec":"info_1",
      "lien_suiv":"info_3",
      "retour":"infographie",
    },

    "info_3": {
      "titre": "CRÉATION LIBRE",
      "categorie": "INFOGRAPHIE 2D ET 3D",
      "type": "Étudiant",
      "duree": "2 mois",
      "equipe": "seule",
      "annee": "2022",
      "contexte": "Chaise 3D réalisée lors d'un projet étudiant que j'ai du promouvoir à l'aide d'une affiche et d'une bannière pour le web. <br> <br> <ul> logiciels utilisés: <li> 3DS max </li> <li> Illustrator </li> <li> Photoshop </li> ",
      "plus":'<a class="pdf" href="pdf/info_3.pdf" target="_blank"> Voir plus </a>',
      "lien_prec":"info_2",
      "lien_suiv":"info_4",
      "retour":"infographie",
    },

    "info_4": {
      "titre": "IDENTITÉ VISUELLE",
      "categorie": "INFOGRAPHIE 2D",
      "type": "Personnel",
      "duree": "en cours",
      "equipe": "seule",
      "annee": "2022-2023",
      "contexte": "Réalisation d'un logo, d'une bannière (en cours) et d'affiches pour l'école maternelle Libermann d'Illkirch-Graffenstaden <br> <br> J'ai crée charte graphique à partir des couleurs assez atypiques de la façade du bâtiment de l'école, afin de rendre les visuels cohérents et évocateurs. <br> <br> <ul> Logiciels utilisés: <ul> <li> Illustrator </li> <li> Photoshop </li> </ul>",
      "plus":'<a class="pdf" href="pdf/info_4.pdf" target="_blank"> Voir plus </a>',
      "lien_prec":"info_3",
      "lien_suiv":"info_5",
      "retour":"infographie",
    },

    "info_5": {
      "titre": "LOGO POUR ASSOCIATION",
      "categorie": "INFOGRAPHIE 2D",
      "type": "Étudiant",
      "duree": "2 mois",
      "equipe": "seule",
      "annee": "2023",
      "contexte":" Réalisation d'un logo pour l'association CAWAL'TAG, dans le cadre d'un projet étudiant. <br> <br> CAWAL'TAG, comité Associatif de Walheim et Tagolsheim a pour objectif de dynamiser ses communes en proposant des activités pour les enfants et les adultes. <br> <br> Le logo devait être sportif, dynammique, convivial, strucuturé et artistique. <br> <br> Malheureusement, il n'a pas été retenu.<br> <br> <ul> Logiciel utilisé: <li> Illustrator </li> </ul>",
      "plus":'<a class="pdf" href="pdf/info_5.pdf" target="_blank"> Voir plus </a>',
      "lien_prec":"info_4",
      "lien_suiv":"info_6",
      "retour":"infographie",
    },

    "info_6": {
      "titre": "LOGO POUR ASSOCIATION",
      "categorie": "INFOGRAPHIE 2D",
      "type": "Personnel",
      "duree": "2 jours",
      "equipe": "2",
      "annee": "2023",
      "contexte": " Création et animation d'un logo pour une future association d'audiovisuel. <br> <br> <ul> Logiciels utilisés: <li> Illustrator </li> <li> Photoshop </li> <li> After effect </li></ul>",
      "plus":"",
      "lien_prec":"info_5",
      "lien_suiv":"audio_1",
      "retour":"infographie",
    },

    "audio_1": {
      "titre": "VIDÉO POUR LE SERFA DE MULHOUSE",
      "categorie": "AUDIOVISUEL",
      "type": "Étudiant",
      "duree": "1 mois",
      "equipe": "3",
      "annee": "2023",
      "contexte": "Mon groupe et moi avons eu la chance d'être sélectionnés par le SERFA, pour une vidéo promotionnelle de leur enseigne, qui fait suite à leur demande auprès du département MMI l'IUT de Mulhouse. <br> <br> Nous attendons avec impatience que la vidéo soit postée sur leurs réseaux afin de pouvoir vous la partager. <br> <br> <ul> Logiciels utilisés : <li> Première pro </li> <li> After effects </li></ul>",
      "plus":"",
      "lien_prec":"info_6",
      "lien_suiv":"audio_2",
      "retour":"audiovisuel",
    },

    "audio_2": {
      "titre": "VIDÉO IMPACT POSITIF",
      "categorie": "AUDIOVISUEL",
      "type": "Étudiant",
      "duree": "2 mois",
      "equipe": "4",
      "annee": "2022",
      "contexte": "Dans le cadre de mes études, nous avions à réaliser en groupe une vidéo sur le thème 'impact positif'. Il s'agit ici de ma première vidéo. <br> <br> Mon groupe et moi avons décidé de montrer l'impact positif du sport dans nos vies quotidienne, des sports de combats plus particulièrement. <br> <br> Ainsi notre vidéo se divise en 2 parties, une partie 'documentaire' qui nous expose les bienfaits du karaté et une autre qui s'apparente à un mini 'film d'action'. Cette deuxième partie a été très intéressante à filmer et nous avons trouvé judicieux de l'ajouter afin de susciter l'intérêt du spectateur.<br> <br> <ul> Matériel utilisé: <li> GH5 </li> <li>ZOOM H5 </li> <li> micro cravate </li> <li> Stabilisateur épaule </li> </ul> <br> <ul> Logiciel utilisé: <li> Davinci resolve </li> </ul>",
      "plus":"",
      "lien_prec":"audio_1",
      "lien_suiv":"progra_1",
      "retour":"audiovisuel",
    },

    "progra_1": {
      "titre": " MON PORTFOLIO ",
      "categorie": "PROGRAMMATION",
      "type": "Étudiant et Personnel",
      "duree": "en cours",
      "equipe": "seule",
      "annee": "2023",
      "contexte": "J'ai réalisé ce portfolio en utilisant les langages de programmation HTML, CSS et JavaScript. <br> <br> Bien que j'aie choisi le parcours création numérique de ma formation, je suis intéressée par le développement web et aimerait acquérir un maximum de compétences en autodidacte. <br> <br> <ul> Logiciel utilisé: <li> Visual Studio code </li> ",
      "plus":"",
      "lien_prec":"audio_2",
      "lien_suiv":"info_1",
      "retour":"programmation",
    },
}
